inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - config/environments/production.rb
    - config/initializers/*
    - db/schema.rb
    - db/migrate/*
    - app/controllers/pieces_controller.rb
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 85

Style/ClassAndModuleChildren:
  Enabled: false

Style/FileName:
  Exclude:
    - Gemfile
